---
engines:
  duplication:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Design/TooManyMethods:
        enabled: false
      UnusedFormalParameter:
        enabled: false
languages:
  Ruby: false
  JavaScript: false
  Python: false
  PHP: true
exclude_paths:
  - tests/*
  - vendor/*
