language: php

php:
  - 5.5-precise
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - hhvm-nightly

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: vendor/bin/phpunit

after_script:
  - ./codeclimate.sh